name: Github Hosted
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
jobs:
  Prepare:
    runs-on: ubuntu-latest
    env:
      ETH0_NAME: ${{ vars.ETH0_NAME }}
      ETH0_BR: ${{ vars.ETH0_BR }}
      ETH0_ADDRESSES: ${{ vars.ETH0_ADDRESSES }}
      ETH1_NAME: ${{ vars.ETH1_NAME }}
      ETH1_BR: ${{ vars.ETH1_BR }}
      ETH1_ADDRESSES: ${{ vars.ETH1_ADDRESSES }}
      ETH2_NAME: ${{ vars.ETH2_NAME }}
      ETH2_BR: ${{ vars.ETH2_BR }}
      ETH2_ADDRESSES: ${{ vars.ETH2_ADDRESSES }}
      NETWORK_MODE: ${{ vars.NETWORK_MODE }}
      TEMPLATE_DIR: ${{ vars.TEMPLATE_DIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Template Directory
        run: mkdir -p $TEMPLATE_DIR
        
      - name: Generate Libvirt Network
        run: |
              source scripts/generate-network.sh
              generate_net
      
      - uses: hashicorp/setup-terraform@v3
      - name: Validate Terraform Template
        id: validate
        run: |
              cd $TEMPLATE_DIR
              terraform init
              terraform validate

      - name: Upload template as artifact
        uses: actions/upload-artifact@v4
        if: steps.validate.outcome == 'success'
        with:
          name: Libvirt_Network_Template
          path: ${{ vars.TEMPLATE_DIR}}/cluster-network.tf
          overwrite: true

  # Checking:
  #   needs: Prepare
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checking Libvirt Network
  #       id: ssh
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.LAB7_HOST }}
  #         username: ${{ secrets.LAB7_USER }}
  #         key: ${{ secrets.LAB7_KEY }}
  #         script: |
  #           ssh -t ${{ secrets.DIRECTOR }} \
  #           'if [[ -n $(virsh net-list|grep "${{ vars.ETH0_NAME}}\|${{ vars.ETH0_NAME}}\|${{ vars.ETH0_NAME}}") ]];
  #           then echo libvirt network exists;
  #           exit 1;
  #           else
  #           exit 0;
  #           fi'
  # Apply:
  #   needs: 
  #     - Prepare
  #     - Checking
  #   runs-on: ubuntu-latest
  #   # if: needs.Checking.result == 'success'
  #   steps:
  #     - name: Copy Libvirt Network Template
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: Libvirt_Network_Template
  #         path: distfiles
  #     - uses: appleboy/scp-action@v0.1.7
  #       with:
  #         host: ${{ secrets.LAB7_HOST }}
  #         username: ${{ secrets.LAB7_USER }}
  #         password: ${{ secrets.PASSWORD }}
  #         key: ${{ secrets.LAB7_KEY }}
  #         source: distfiles/*
  #         target: ${{ secrets.MYDIR }}
  #     - name: Applying Libvirt Network
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.LAB7_HOST }}
  #         username: ${{ secrets.LAB7_USER }}
  #         key: ${{ secrets.LAB7_KEY }}
  #         script: |
  #           ls -lh ${{ secrets.MYDIR }}