name: Github Hosted
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
jobs:
  Prepare:
    runs-on: ubuntu-latest
    env:
      ETH0_NAME: ${{ vars.ETH0_NAME }}
      ETH0_BR: ${{ vars.ETH0_BR }}
      ETH0_ADDRESSES: ${{ vars.ETH0_ADDRESSES }}
      ETH1_NAME: ${{ vars.ETH1_NAME }}
      ETH1_BR: ${{ vars.ETH1_BR }}
      ETH1_ADDRESSES: ${{ vars.ETH1_ADDRESSES }}
      ETH2_NAME: ${{ vars.ETH2_NAME }}
      ETH2_BR: ${{ vars.ETH2_BR }}
      ETH2_ADDRESSES: ${{ vars.ETH2_ADDRESSES }}
      NETWORK_MODE: ${{ vars.NETWORK_MODE }}
      TEMPLATE_DIR: ${{ vars.TEMPLATE_DIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Create template directory
        run: mkdir -p $TEMPLATE_DIR
        
      - name: Generate libvirt network
        run: |
              source scripts/generate-network.sh
              generate_net
      
      - uses: hashicorp/setup-terraform@v3
      - name: Validate terraform template
        id: validate
        run: |
              cd $TEMPLATE_DIR
              terraform init
              terraform validate

      - name: Upload template as artifact
        uses: actions/upload-artifact@v4
        if: steps.validate.outcome == 'success'
        with:
          name: libvirt_network_template
          path: ${{ vars.TEMPLATE_DIR}}/cluster-network.tf
          overwrite: true

  Checking:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checking libvirt network
        id: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LAB7_HOST }}
          username: ${{ secrets.LAB7_USER }}
          key: ${{ secrets.LAB7_KEY }}
          script: |
            ssh -t ${{ secrets.DIRECTOR }} \
            'if [[ -n $(virsh net-list|grep "${{ vars.ETH0_NAME}}\|${{ vars.ETH0_NAME}}\|${{ vars.ETH0_NAME}}") ]];
            then echo libvirt network exists;
            exit 1;
            else
            exit 0;
            fi'
  Apply:
    needs: 
      - Prepare
      - Checking
    runs-on: ubuntu-latest
    # if: ${{ needs.Checking.result != 'success'}}
    steps:
      - name: Download artifact template
        uses: actions/download-artifact@v4
        if: ${{ steps.ssh.outcome != 'success'}}
        with:
          name: libvirt_network_template
          path: ${{ github.repository }}
      - name: Copy libvirt network
        uses: appleboy/scp-action@v0.1.7
        if: ${{ steps.ssh.outcome != 'success'}}
        with:
          host: ${{ secrets.LAB7_HOST }}
          username: ${{ secrets.LAB7_USER }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.LAB7_KEY }}
          source: ${{ github.repository}}/*
          target: ${{ secrets.MYDIR }}
      - name: Applying libvirt network
        uses: appleboy/ssh-action@v1.0.3
        if: ${{ steps.ssh.outcome == 'success'}}
        with:
          host: ${{ secrets.LAB7_HOST }}
          username: ${{ secrets.LAB7_USER }}
          key: ${{ secrets.LAB7_KEY }}
          script: |
            ls -lh ${{ secrets.MYDIR }}