# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Prepare:
    # environment:
    #   name: Manual
    env:
      Hello: Konnichiwa
      ETH0: ${{ vars.BR_ETH0 }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      # - name: Check User Info
      #   run: |
      #         id
      #         pwd
      # - name: Checkout to root
      #   run: sudo su
      - name: Variable Test
        run: |
              echo $Hello
              echo $ETH0
      - name: Check List Var
        run: env
  # Setup:
  #   needs: Prepare
  #   environment:
  #     name: Manual
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@main
  #     - name: Check RAM Info
  #       run: free -h

  
