# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Prepare:
    # environment:
    #   name: Manual
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: Check User Info
        run: |
              id
              pwd
      - name: Checkout to root
        run: sudo su
      - name: Creating Terraform Network
        run: |
              mkdir -p network
              cat <<EOF > network/cluster-network.tf
              provider "libvirt" {
                  uri = "qemu:///system"
              }
              
              terraform {
               required_version = ">= 0.13"
                required_providers {
                  libvirt = {
                    source  = "dmacvicar/libvirt"
                    version = "0.7.1"
                  }
                }
              }
              
              // Network Section
              resource "libvirt_network" "eth0" {
                  name = "net-dont-use-eth0"
                  mode = "nat"
                  bridge = "br-192.168.251"
                  addresses = ["192.168.251.0/24"]
                  dhcp {
                      enabled = true
                  }
              }
              
              resource "libvirt_network" "eth1" {
                  name = "net-dont-use-eth1"
                  mode = "nat"
                  bridge = "br-192.168.236"
                  addresses = ["192.168.236.0/24"]
                  dhcp {
                      enabled = true
                  }
              }
              
              resource "libvirt_network" "eth2" {
                  name = "net-dont-use-eth2"
                  mode = "nat"
                  bridge = "br-192.168.237"
                  addresses = ["192.168.237.0/24"]
                  dhcp {
                      enabled = true
                  }
              }
              
              resource "libvirt_network" "eth3" {
                  name = "net-dont-use-eth3"
                  mode = "nat"
                  bridge = "br-192.168.216"
                  addresses = ["192.168.216.0/24"]
                  dhcp {
                      enabled = true
                  }
              }
              
              resource "libvirt_network" "eth4" {
                  name = "net-dont-use-eth4"
                  mode = "nat"
                  bridge = "br-192.168.224"
                  addresses = ["192.168.224.0/24"]
                  dhcp {
                      enabled = true
                  }
              }
              
              resource "libvirt_network" "eth5" {
                  name = "net-dont-use-eth5"
                  mode = "nat"
                  bridge = "br-192.168.238"
                  addresses = ["192.168.238.0/24"]
                  dhcp {
                      enabled = true
                  }
              }
              
              resource "libvirt_network" "eth6" {
                  name = "net-dont-use-eth6"
                  mode = "nat"
                  bridge = "br-192.168.239"
                  addresses = ["192.168.239.0/24"]
                  dhcp {
                      enabled = true
                  }
              }
              EOF
              cat network/cluster-network.tf
              id
  # Setup:
  #   needs: Prepare
  #   environment:
  #     name: Manual
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@main
  #     - name: Check RAM Info
  #       run: free -h

  
