name: CI
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
jobs:
  Prepare:
    env:
      ETH0: ${{ vars.BR_ETH0 }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: Generate Libvirt Network
        run: |
              cat <<EOF> cluster-network.tf
              provider "libvirt" {
                  uri = "qemu:///system"
              }
              
              terraform {
               required_version = ">= 0.13"
                required_providers {
                  libvirt = {
                    source  = "dmacvicar/libvirt"
                    version = "0.7.1"
                  }
                }
              }
              
              // Network Section
              resource "libvirt_network" "eth0" {
                  name = "net-dont-use-eth0"
                  mode = "nat"
                  bridge = "$ETH0"
                  addresses = ["192.168.251.0/24"]
                  dhcp {
                      enabled = true
                  }
              }
              EOF
              cat cluster-network.tf
      # - name: Check User Info
      #   run: |
      #         id
      #         pwd
      # - name: Checkout to root
      #   run: sudo su
  # Setup:
  #   needs: Prepare
  #   environment:
  #     name: Manual
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@main
  #     - name: Check RAM Info
  #       run: free -h

  
