name: CI
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
jobs:
  Prepare:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: Generate Libvirt Network
        run: |
              source scripts/generate-network.sh
              ls -R
              # cat cluster-network.tf
      # - name: Check User Info
      #   run: |
      #         id
      #         pwd
      # - name: Checkout to root
      #   run: sudo su
  # Setup:
  #   needs: Prepare
  #   environment:
  #     name: Manual
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@main
  #     - name: Check RAM Info
  #       run: free -h

  
